### ISSUE TITLE
Backend goals

### ISSUE THREAD

**Issue by seankcheema** [seankcheema/QuestList#2]
These are the backend goals developed by Sean and Javier

**Setup:**
-Find working library of games
-Find database of games and their global rankings
-Create Game struct to store game data in our own library? ((MAYBE))
-Be able to regurgitate game data in a readable way
-Find out how to link back end and front end

**Users:**
-Create user struct
-Each user has unique usernames and their own password
-Create database of users

**Comment by JJRaderFTW** [comment]
First objective will be working on setup. Will find library and interpret it

**Comment by seankcheema** [comment]
Basic user struct has been created. Also added a map for these users checking if the username is unique before adding it to the map.

**Comment by seankcheema** [comment]
Database of users has been created and back end/front end have been linked.
