### ISSUE TITLE
Basic Issue: Establishing Back and Front End Communications 

### ISSUE THREAD

**Issue by JJRaderFTW** [seankcheema/QuestList#3]
I would like to **establish a concrete way of communication between front end and the back end** for the purpose of knowing how the back end (GoLang) will send and receive information from the front end (Angular) each other when each end of the program is written.**

_Rational:_ I want to develop and set up variables and routers that can can encode and decode files that come from the front end. I want some mechanism that will interpret request (such as “/“ and “GET” or “/user” and “PUSH” in a url) and pass it into the back end. The back end mechanism can then interpret what is wanted and call the correct methods to achieve each requested task (such as encoding or decoding a json file). The back end will then return to the front end some form of confirmation that the requested task was done. 

<sub>[Success in this task will be determined when trivial code is able to be exchanged between both the Angular code and GoLang code]</sub>

**Comment by seankcheema** [comment]
We used http client module (front end) and mux (back end) to establish communication between the two sides.
