### ISSUE TITLE
User Story: Sign up

### ISSUE THREAD

**Issue by seankcheema** [seankcheema/QuestList#7]
**User Story** <hr />As a **new user**, I would like to **sign up and create an account** for the purpose of **saving my activity on the site**
<br />
**Implementation Details** <hr /> 

- Implemented by front and back end
- Create form gui
- Add users to user database in backend
<br />

**Importance:** \*\*\*
**Expected Difficulty:** \*\*\*

**Comment by JJRaderFTW** [comment]
Front and back-end have finished all goals for making a signup page and storing user data
