### ISSUE TITLE
User Story: Login

### ISSUE THREAD

**Issue by seankcheema** [seankcheema/QuestList#8]
**User Story** <hr />As a **returning user** I would like to **log into the website** for the purpose of **seeing my previous activity on the site**
<br />
**Implementation Details** <hr /> 

- Implemented by front and back end
- Front end create login gui
- Back end get user information
<br />

**Importance:** \*\*\*
**Expected Difficulty:** \*\*

**Comment by seankcheema** [comment]
Back end has created functionality for login but is still in need of unit testing

**Comment by JJRaderFTW** [comment]
Both front and back-end have finished all factors associated with a login GUI and retrieving users
