### ISSUE TITLE
User Story: Game Library 

### ISSUE THREAD

**Issue by JJRaderFTW** [seankcheema/QuestList#9]
**User Story** <hr />As a **website visiter** I would like to **have access and see a list of all the games documented on the website** for the purpose of **knowing what I would like to add to my user library**.
<br />
**Implementation Details** <hr /> 

- Finding a useable public database of most available games in the market to use as our back bone for the video games users can add to their libraries 
- Create a filter function that can search for games in the list in a time sensitive manner
- Implemented by front and back end 
- Front end handles game information display 
- Back end handles library importing and file traversal
<br />

**Importance:** \*\*\*
**Expected Difficulty:** \*\

**Comment by JJRaderFTW** [comment]
Found a very good web-based API that includes game lists, developers, pictures, and other useful content. This database is ideal but requires an Access Code that we do not have until we get a working URL. We emailed the owners for access and await a response.

Website: https://rawg.io/

**Comment by JJRaderFTW** [comment]
In the mean times, we found a decent github-based database that uses SQL files called DataBaseStar to store game names, developers, and platforms. Its a lot more basic but is way more accessible than Rawg. If we can use Rawg we will, but will continue with DataBaseStar for now to create a working database interpreter and means of traversal. We created local versions of the SQL files and will use GORM/SQL to access them.

Website: https://discord.com/channels/1063557932094062643/1069728515248881704/1069756726355710112

**Comment by JJRaderFTW** [comment]
We managed to secure an access code for the RAWG API. We also found and implemented an library from github that helps deal with API requests. We will continue working with RAWG to create a readable database/backbone for our website.

**Comment by seankcheema** [comment]
We learned how to connect and traverse the Database using RAWG SDK library. We can search and print games and their details to local host

**Comment by seankcheema** [comment]
All functionalities met at this time except for front end display

**Comment by seankcheema** [comment]
Front end display functionality has been met.
